Name:           ros-hydro-diff-drive-controller
Version:        0.7.3
Release:        0%{?dist}
Summary:        ROS diff_drive_controller package

Group:          Development/Libraries
License:        BSD
URL:            https://github.com/ros-controls/ros_controllers/wiki
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-controller-interface
Requires:       ros-hydro-nav-msgs
Requires:       ros-hydro-realtime-tools
Requires:       ros-hydro-tf
Requires:       ros-hydro-urdf
BuildRequires:  ros-hydro-angles
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-controller-interface
BuildRequires:  ros-hydro-controller-manager
BuildRequires:  ros-hydro-nav-msgs
BuildRequires:  ros-hydro-realtime-tools
BuildRequires:  ros-hydro-rostest
BuildRequires:  ros-hydro-tf
BuildRequires:  ros-hydro-urdf
BuildRequires:  ros-hydro-xacro

%description
Controller for a differential drive mobile base.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Oct 28 2014 Bence Magyar <bence.magyar@pal-robotics.com> - 0.7.3-0
- Autogenerated by Bloom

